### ISSUE TITLE
Thanks for it and build request

### ISSUE THREAD

**Issue by icaromh** [daneden/muffler#2]
Hey 👋! 
First of all, this is all I need and didn't know until reading the repository description. 
Congratulations 🥳 

May I request build it for MacOS 10.15 as well? 🥺

![image](https://user-images.githubusercontent.com/3057676/101369648-768ff200-38a0-11eb-8eee-303bd9ae52a3.png)

**Comment by daneden** [comment]
Hey @icaromh! Yes, this is definitely on my to-do list; I’ll try to fix that ASAP!

**Comment by daneden** [comment]
Fixed in bd9ca97c27f82590f537cea0e67229615c1b25e4!
